=== mCRL2org/mCRL2/src/squadt/schemas/tool_catalog.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <!-- A version specification type -->
 <xs:simpleType name="version-type">
  <xs:restriction base="xs:token">
   <xs:pattern value="[0-9]+\.[0-9]+"/>
  </xs:restriction>
 </xs:simpleType>
 <!-- Data type for tool/specification identification -->
 <xs:simpleType name="identifier">
  <xs:restriction base="xs:token">
   <xs:pattern value="[a-z][a-z0-9_]+"/>
  </xs:restriction>
 </xs:simpleType>
 <!-- Element used to relate a command line option to the format of an object -->
 <xs:complexType name="format-selector">
  <xs:simpleContent>
   <xs:extension base="xs:token">
    <xs:attribute name="format" type="xs:token" use="required"/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 <!-- Type of an object either input or output -->
 <xs:simpleType name="object-type">
  <xs:restriction base="xs:string">
   <xs:pattern value="input|output"/>
  </xs:restriction>
 </xs:simpleType>
 <!-- Type for a tool mode of operation specification -->
 <xs:complexType name="mode-specifier">
  <xs:sequence>
   <xs:element name="description" type="xs:token" minOccurs="0"/>
   <xs:element name="object" type="object-specifier" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="category" type="xs:token" use="required"/>
  <xs:attribute name="selector" type="xs:string" use="optional"/>
 </xs:complexType>
 <!-- Element for specification of tool input and output objects -->
 <xs:complexType name="object-specifier">
  <xs:sequence>
   <xs:element name="format-selector" type="format-selector" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="type" type="object-type" use="required"/>
  <xs:attribute name="selector" type="xs:string" use="optional"/>
  <xs:attribute name="name" type="xs:token" use="optional"/>
  <xs:attribute name="formalism" type="xs:token" use="required"/>
  <xs:attribute name="default-format" type="xs:token" use="optional"/>
  <xs:attribute name="virtual" type="xs:boolean" use="optional"/>
 </xs:complexType>
 <!-- Element for specification of a single tool profile -->
 <xs:complexType name="tool-profile">
  <xs:sequence>
   <xs:element name="description" type="xs:token"/>
   <xs:element name="mode" type="mode-specifier" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:token" use="required"/>
  <xs:attribute name="identifier" type="identifier" use="required"/>
  <xs:attribute name="location" type="xs:token" use="required"/>
 </xs:complexType>
 <!-- Root element the tool-catalog -->
 <xs:element name="tool-catalog">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="tool" type="tool-profile" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="version" type="version-type" use="required"/>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== mCRL2org/mCRL2/tools/release/mcrl2-gui/share/mcrl2/tool_catalog.xml
<?xml version="1.0" encoding="utf-8"?>
<tool-catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tool_catalog.xsd" version="1.0">
<tool name="besinfo"            input_format="bes"                        category="Analysis"/>
<tool name="bespp"              input_format="bes"   output_format="txt"  category="Analysis"/>

<tool name="diagraphica"        input_format="lts"                        category="Analysis"       gui="true" />

<tool name="lps2lts"            input_format="lps"   output_format="lts"  category="Transformation"/>
<tool name="lps2pbes"           input_format="lps"   output_format="pbes" category="Transformation" />
<tool name="lpsbisim2pbes"	input_format="lps"   output_format="pbes" category="Transformation"/>
<tool name="lpsactionrename"    input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsbinary"          input_format="lps"   output_format="lps"  category="Transformation"/> 
<tool name="lpsconfcheck"       input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsconstelm"        input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsinfo"            input_format="lps"                        category="Analysis"/>
<tool name="lpsinvelm"          input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsparelm"          input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsparunfold"       input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpspp"              input_format="lps"   output_format="txt"  category="Analysis"/>
<tool name="lpsrewr"            input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpssumelm"          input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpssuminst"         input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsuntime"          input_format="lps"   output_format="lps"  category="Transformation"/>
<tool name="lpsxsim" 		input_format="lps"                        category="Analysis" gui="true"/>
<tool name="lts2lps" 		input_format="lts"   output_format="lps"  category="Transformation"/>
<tool name="lts2pbes" 		input_format="lts"   output_format="pbes" category="Transformation"/>
<tool name="ltsconvert" 	input_format="lts"   output_format="lts"  category="Transformation"/>
<tool name="ltscompare" 	input_format="lts"   input_format1="lts"  category="Analysis"/>
<tool name="ltsgraph" 		input_format="lts"                        category="Analysis" gui="true" />
<tool name="ltsinfo" 		input_format="lts"                        category="Analysis"/>
<tool name="ltsview" 		input_format="lts"                        category="Analysis" gui="true" />

<tool name="mcrl22lps" 		input_format="mcrl2" output_format ="lps" category="Transformation"/> 
<tool name="mcrl2xi" 		input_format="mcrl2"                      category="Editing" gui="true"/>

<tool name="pbes2bool" 		input_format="pbes;bes"                   category="Analysis"/>
<tool name="pbes2bes" 		input_format="pbes" output_format="bes"   category="Transformation"/>
<tool name="pbesinst" 		input_format="pbes" output_format="pbes"  category="Transformation"/>
<tool name="pbesconstelm" 	input_format="pbes" output_format="pbes"  category="Transformation"/> 
<tool name="pbesinfo" 		input_format="pbes"                       category="Analysis"/>
<tool name="pbesparelm" 	input_format="pbes" output_format="pbes"  category="Transformation"/>
<tool name="pbespgsolve" 	input_format="pbes;bes"                   category="Analysis"/>
<tool name="pbespp" 		input_format="pbes" output_format="txt"   category="Analysis"/>
<tool name="bessolve" 		input_format="bes"  output_format="txt"   category="Analysis"/>
<tool name="pbesrewr" 		input_format="pbes" output_format="pbes"  category="Transformation"/>

<tool name="tracepp" 		input_format="trc"  output_format="txt"   category="Analysis"/>
<tool name="txt2lps" 		input_format="txt"  output_format="lps"   category="Transformation"/>
<tool name="txt2bes" 		input_format="txt"  output_format="bes"   category="Transformation"/>
<tool name="txt2pbes" 		input_format="txt"  output_format="pbes"  category="Transformation"/>
</tool-catalog>

=== mCRL2org/mCRL2/src/studio/examples/tool_catalog.xml
<?xml version="1.0" encoding="utf-8"?>
<tool-catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tool_catalog.xsd">
 <tool name="lpe2lts" identifier="lpe2lts" location="/tmp/mcrl2/bin/lpe2lts">
  <description>A tool computes the instantiation of an LPE.</description>
  <mode category="Translation">
   <object type="input" name="%.lpe" formalism="LPE" default-format="lpe"/>
   <object type="output" name="%.aut" formalism="LTS" default-format="aut">
    <format-selector format="svc">--svc</format-selector>
   </object>
  </mode>
  <mode category="Analysis" selector="--deadlock-detect">
   <description>Performs a deadlock detection and does not store state space</description>
   <object type="input" name="%.lpe" formalism="LPE" default-format="lpe"/>
  </mode>
 </tool>
 <tool name="mcrl22lpe" identifier="mcrl22lpe" location="/tmp/mcrl2/bin/mcrl22lpe">
  <mode category="Translation">
   <description>A tool that transforms mCRL2 specification to an LPE.</description>
   <object type="input" name="%.mcrl2" formalism="mCRL2" default-format="mcrl2"/>
   <object type="output" name="%.lpe" formalism="LPE" default-format="lpe"/>
  </mode>
 </tool>
 <tool name="lpeconstelm" identifier="lpeconstelm" location="/tmp/mcrl2/bin/lpeconstelm">
  <mode category="Transformation">
   <description>A tool that transforms an LPE to an LPE where constants are eliminated.</description>
   <object type="input" formalism="LPE" default-format="lpe"/>
   <object type="output" formalism="LPE" default-format="lpe"/>
  </mode>
 </tool>
</tool-catalog>
